DjangoWebProject5/DjangoWebProject5/urls.py
"""
Definition of urls for DjangoWebProject5.
"""

from django.conf.urls import include, url
from home.views import home_view

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', DjangoWebProject5.views.home, name='home'),
    # url(r'^DjangoWebProject5/', include('DjangoWebProject5.DjangoWebProject5.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
      url(r'^admin/', include(admin.site.urls)),
      url(r'^$',home_view, name='home'),
      url(r'^post/', include('post.urls')),
      url(r'^accounts/', include('accounts.urls')),

]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

DjangoWebProject5/accounts/urls.py
from django.conf.urls import include, url
from .views import *
app_name='accounts'

urlpatterns = [
     url(r'^login/$',login_view,name='login'),

     url(r'^register/$',register_view,name='register'),

     url(r'^logout/$',logout_view,name='logout'),
    
]


DjangoWebProject5/post/urls.py
from django.conf.urls import include, url
from post.views import *
app_name='post'

urlpatterns = [
     url(r'^index$',post_index,name='index'),
     url(r'^create$',post_create, name='create'),
     url(r'^(?P<slug>[\w-]+)/$',post_detail,name='detail'),
     url(r'^(?P<slug>[\w-]+)/update$',post_update,name='update'),
     url(r'^(?P<slug>[\w-]+)/delete$',post_delete,name='delete'),
]


DjangoWebProject5/home/models.py
from django.db import models

# Create your models here.

DjangoWebProject5/home/views.py
from django.shortcuts import render,HttpResponse


def home_view(request):
    if request.user.is_authenticated():
         context={'isim':'Halil'}
    else:
        context={'isim':'Misafir'}
    return render(request,'home.html',context)

# Create your views here.

DjangoWebProject5/templates/base.html
<!DOCTYPE html>

{%load static%}
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" name="viewport" content="width-device-width, inital-scale=1" />
    <title>{%block title%}Django{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {#<link rel="stylesheet" href="{% static 'style.css'%}">#}
</head>
<body>

    {%include 'header.html'%}
    {% include 'messages.html'%}



    {%block body%}

    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
</body>
</html>

DjangoWebProject5/templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home'%}" class="navbar-brand">Django Dersleri</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{request.GET.q}}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}<!--admin olmayanlara yazı ekle kapatıldı-->
                    <li><a href="{% url 'post:create'%}">Yazı Ekle</a></li>
                {%endif%}
                    <li><a href="{% url 'home'%}">Anasayfa</a></li>
                    <li><a href="{% url 'post:index'%}">Blog</a></li>
                    <li><a href="#">Hakkımda</a></li>
                    <li><a href="#">İletişim</a></li>

                {%if not request.user.is_authenticated %}<!--henüz giriş yapılmamışsa alt tarafı göster-->
                    <li><a href="{% url 'accounts:register'%}">Üye Ol</a></li>
                    <li><a href="{% url 'accounts:login'%}">Giriş</a></li>
                {%else%}
                    <li><a href="{% url 'accounts:logout'%}">Çıkış</a></li>
                {%endif%}
            </ul>

        </nav>

    </div>
</nav>

DjangoWebProject5/templates/home.html

    

{%extends 'base.html'%}

{%block title%}Anasayfa

    {% endblock %}

{%block body%}
<br />
<br />
<br />
<br />
<br />

<div class="container">
   <div class="row">
            
        </div>
    </div>
  
      Hoşgeldin, {{ request.user.username }}
{%endblock%}

DjangoWebProject5/templates/index.html
<html>
<head><title></title></head>

<body>

{{ content }}
    

</body>
</html>

DjangoWebProject5/templates/messages.html


 {% if messages %}   

             {% for message in messages %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {{ message }}   
                </div>
            {% endfor %}
{% endif %}